### ISSUE TITLE
Sentiment Analysis Model not found

### ISSUE THREAD

**Issue by amanm6925** [srbhklkrn/depression-therapist-chatbot#1]
On directly cloning and running bot.py file, I am getting this error
Traceback (most recent call last):
  File "bot.py", line 20, in <module>
    model = load_model('model/model_nn.h5')
  File "/home/aman/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 189, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/home/aman/anaconda3/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 110, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: model/model_nn.h5/{saved_model.pbtxt|saved_model.pb}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 23, in <module>
    raise IOError("Could not find Sentiment Analysis model. Ensure model is present in: ./model")
OSError: Could not find Sentiment Analysis model. Ensure model is present in: ./model

Although I have model_nn.h5 file in model folder.

**Comment by mahnoorabbasi** [comment]
Same issue with me. I also tried getting it using git lfs but it throws the following error.

This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/srbhklkrn/depression-therapist-chatbot-.git/info/lfs'

**Comment by amanm6925** [comment]
Are we supposed to upload some google cloud key in the first line where we upload files to colab?

**Comment by srbhklkrn** [comment]
Hi, sorry for getting back to guys this late, you can download both models from this [link](https://drive.google.com/file/d/1wa9CuGO3y4I-SGDDUfw-qbj2zoGBmfwn/view?usp=sharing)
