### ISSUE TITLE
Can You please provide me the dataset that you have used for training and testing 

### ISSUE THREAD

**Issue by 99anjali** [srbhklkrn/depression-therapist-chatbot#2]
while fetching it using git lfs i am getting the below error
$ git lfs fetch
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/srbhklkrn/depression-therapist-chatbot.git/info/lfs'

**Comment by srbhklkrn** [comment]
you can find the dataset at https://github.com/srbhklkrn/depression-therapist-chatbot/tree/master/model/tweet_data

**Comment by 99anjali** [comment]
Its shows the error mentioned in the description

**Comment by srbhklkrn** [comment]
updated the readme with the dataset link

**Comment by 99anjali** [comment]
Please give me the access..sent the request.

**Comment by srbhklkrn** [comment]
You can download the files with current privileges: 
https://drive.google.com/drive/folders/15uHknTNbKAVsKfe33bcF9q3LHfIFl9Kr?usp=sharing

**Comment by 99anjali** [comment]
Thankyou so much..
